site_name: 'Chunkadocs'
site_url: 'https://docs.chunkadust.com/'
docs_dir: 'docs'
theme:
  name: 'mkdocs'
  features:
    - navigation.tabs
nav:
    - Home: index.md
    - Basics:
        - 'What is a 3D Printer?': 'introduction.md'
        - 'Filament': 'filament.md'
        - 'Slicing': 'slicing.md'
        - 'Bed Types': 'bed_types.md'
        - 'Features': 'features.md'
    - 'Slicer Settings':
        - 'Recommended Slicer Settings': 'slicer_settings.md'
    - 'Recommended Printers':
        - '3D Printer Models': 'popular_models.md'

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list